services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=commitmon
    ports:
      - 3306:3306
  cache:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379