spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

app:
  github:
    token: ${GITHUB_TOKEN}
    base-url: https://api.github.com