spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

app:
  github:
    token: ${GITHUB_TOKEN}
    base-url: https://api.github.com