spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/commitmon
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE