spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

server:
  tomcat:
    relaxed-query-chars: "{,}"

app:
  auth:
    jwt:
      base64-secret: ${JWT_SECRET}
      expired-ms: 3600000 # 1hour
    refresh-token:
      expired-ms: 1209600000 # 2weeks
  github:
    token: ${GITHUB_TOKEN}
    base-url: https://api.github.com
    oauth2:
      base-url: https://github.com/login/oauth
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}