name: SpringBoot APP CI/CD
on:
  push:
    branches: [ main, 58-migration-from-aws-to-ncp ]
jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY_ID }}
          password: ${{ secrets.NCP_SECRET_KEY }}
      - name: Build, tag, and push image to NCP Container Registry
        env:
          NCP_REGISTRY: ${{ secrets.NCP_CONTAINER_REGISTRY_URL }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $NCP_REGISTRY/commitmon:$IMAGE_TAG -t $NCP_REGISTRY/commitmon:latest .
          docker push $NCP_REGISTRY/commitmon --all-tags